name: event_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  get: ^4.6.6
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  media_store_plus: ^0.0.7
  font_awesome_flutter: ^10.6.0
  mime: ^1.0.4
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  dio: ^5.4.0
  permission_handler: ^11.1.0
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  overlay_group_avatar: ^0.0.2
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#181A20"
  adaptive_icon_foreground: "assets/logo_foreground.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
